### ISSUE TITLE
Same referer for any traffic source 

### ISSUE THREAD

**Issue by mixtraff** [uerceg/play-install-referrer-unity#4]
Hi,
I got same referer reply from console . For test I use different traffic sources:
- facebook ads via fb application 
- direct installation from google play without utm params
- direct installation from google play with utm params 
( example: https://play.google.com/store/apps/details?id=com.magic.neon.app&utm_source=mixtraff&utm_medium=ebola)

So result for any traffic source same, please see log details below
`2020-05-01 13:02:39.047 31114-31114/? I/Unity: ReferrerInfo Install referrer: utm_source=(not%20set)&utm_medium=(not%20set)
    <>c:<Start>b__0_0(PlayInstallReferrerDetails)
    BlackBox.PlayInstallReferrerPlugin.InstallReferrerStateListener:onInstallReferrerSetupFinished(Int32)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)`

and

`2020-05-01 13:02:39.056 31114-31114/? I/Unity: ReferrerInfo Google Play instant: False
    <>c:<Start>b__0_0(PlayInstallReferrerDetails)
    BlackBox.PlayInstallReferrerPlugin.InstallReferrerStateListener:onInstallReferrerSetupFinished(Int32)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)`

**Comment by uerceg** [comment]
Hi @mixtraff 

I am not sure this is actually the problem of the plugin itself. This issue originates from the fact that for some reason, Google is not actually setting up your utm parameters properly. I think I saw quite a few of these questions in past few years, for example:

- https://stackoverflow.com/questions/53481131/com-android-vending-install-referrer-somehow-parameters-are-lost-and-changed-t/54884659#54884659
- https://stackoverflow.com/questions/38940155/when-will-the-application-receive-a-install-referrer-with-content-utm-source-no
- https://medium.com/@mehmetdelikaya/how-to-track-google-play-store-installs-in-your-android-app-91cafb9f7ecc

Let me know if any of the suggestions from these pages in how to test the referrer value worked for you.

Cheers

**Comment by mixtraff** [comment]
Hi,
I need some help with this module . Is it possible to detect paid traffic from facebook  or google ads using such module? I ready to pay for this help. 
My contact details:  
telegram @mixtraff
skype x.wadik

**Comment by uerceg** [comment]
Hi @mixtraff 

This plugin itself is agnostic towards source of your app's installs. Your users can come to Play Store to download your app from various sources (Google, Facebook, any other campaigns) and this information is usually something you can find inside of install referrer content. 

This plugin is just a simple wrapper around Google's install referrer library which gives you back information about referrer content. Google built the library just for native Android apps and I just built this small plugin on top of it to provide Unity users simple API to get same information about install referrer like native Android app developers are able to.

Plugin does not distinguish what is the marketing channel which brought you the user, so if user is coming from FB/Google campaigns - this is something you should figure out on your own based on install referrer content. 

To be honest, I am not even sure how this would be done in plugin. Sure, some parsing logic to determine if install referrer contains some FB/Google specific parameters I guess, but I have no experience in how campaign URLs are set up nor how to look for such information in there. Even if I knew that, it would not be built into this plugin, since it's not its real purpose. 

Cheers

**Comment by mixtraff** [comment]
I found this information :
`We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.`
are you sure that your plugin still working?

**Comment by uerceg** [comment]
Yes.

This message refers to obtaining install referrer content with old, nowdays deprecated, way where Play Store app used **INSTALL_REFERRER** intent to pass referrer information into the app upon first app opening. In order for this to work, app needed to define custom broadcast receiver which was listening for this intent and obtain information in this way. Google has deprecated this approach since March 1st 2020 in favour of new install referrer library they developed few years ago. This Unity plugin is a wrapper on top of install referrer library which is preferred way these days how install referrer information should be obtained.

**Comment by uerceg** [comment]
@mixtraff In case you have any other questions, feel free to comment/reopen.

Cheers
