### ISSUE TITLE
Problem with Facebook sdk

### ISSUE THREAD

**Issue by hungrygamedev** [uerceg/play-install-referrer-unity#5]
I have a problem building apk from Facebook sdk. Duplicate classes in aar, between your plugin and Facebook.

**Comment by uerceg** [comment]
Oh, interesting. Can happen because FB is also pulling install referrer dependency directly from AAR they pack inside. I will try to reproduce this. Can you send me the link to FB plugin you are using in your app?

**Comment by hungrygamedev** [comment]
Ok. https://developers.facebook.com/docs/unity/

**Comment by hungrygamedev** [comment]
I tried to combine, but everything is even. I think you need to watch FB aar instead of yours.

**Comment by uerceg** [comment]
@hungrygamedev 

I just tried to build APK from Unity with **play-install-referrer-unity** and FB plugin added, build finished successfully. I haven't done anything with FB SDK except adding it to the project. Do I need to do something in particular with it to reproduce the error you're facing?

**Comment by uerceg** [comment]
@hungrygamedev Also if you can send me error message you are seeing when trying to build an app, would be useful. After just adding the FB Unity SDK and building an app in Android Studio (even though I am struggling to make it run, see comment above) I can't see any reference to native play install referrer library from Unity FB SDK (that's why I am able to successfully build the app). I have also unpacked FB's AAR they are packing into `libs` directory and which exists next to play install referrer AAR my plugin is adding and I also found nothing inside which references play install referrer library. 

So would be great if you can maybe explain how can I set up my app to be able to reproduce what you are seeing (maybe I need to do some additional configuration steps with FB SDK?).

Cheers

**Comment by hungrygamedev** [comment]
First you need to configure the initialization of the FB. https://developers.facebook.com/docs/unity/getting-started/android

After that, in unity, I am doing a resolve and that’s good.
После я инициализирую в коде FB.
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Facebook.Unity;
using BlackBox.PlayInstallReferrerPlugin;
public class FacebookInit : MonoBehaviour
{
    string installReferrer;

    void Awake()
    {
        AndroidJNIHelper.debug = true;

        if (!FB.IsInitialized)
        {
            FB.Init(InitCallback);
        }
        else
        {
            FB.ActivateApp();
        }
    }
    private void InitCallback()
    {
        if (FB.IsInitialized)
        {
            FB.ActivateApp();
        }
        else
        {
            Debug.Log("Failed to Initialize the Facebook SDK");
        }
    }

    void Start()
    {
        installReferrer = "";

        PlayInstallReferrer.GetInstallReferrerInfo((installReferrerDetails) =>
         {
             Debug.Log("Install referrer details received!");

              if (installReferrerDetails.Error != null)
             {
                 Debug.LogError("Error occurred!");
                 if (installReferrerDetails.Error.Exception != null)
                 {
                     Debug.LogError("Exception message: " + installReferrerDetails.Error.Exception.Message);
                 }
                 Debug.LogError("Response code: " + installReferrerDetails.Error.ResponseCode.ToString());
                 return;
             }else
             {
                 installReferrer = installReferrerDetails.Error.ToString();
             }

              if (installReferrerDetails.InstallReferrer != null)
             {
                 Debug.Log("Install referrer: " + installReferrerDetails.InstallReferrer);
                 ///--------------------------------------///
                 installReferrer = installReferrerDetails.InstallReferrer.ToString();
                 ///--------------------------------------///
             }
             if (installReferrerDetails.ReferrerClickTimestampSeconds != null)
             {
                 Debug.Log("Referrer click timestamp: " + installReferrerDetails.ReferrerClickTimestampSeconds);
             }
             if (installReferrerDetails.InstallBeginTimestampSeconds != null)
             {
                 Debug.Log("Install begin timestamp: " + installReferrerDetails.InstallBeginTimestampSeconds);
             }
             if (installReferrerDetails.GooglePlayInstant != null)
             {
                 Debug.Log("Google Play instant: " + installReferrerDetails.GooglePlayInstant);
             }
         });

        Debug.Log("///--------------------------/-" + installReferrer + "-/--------------------------///");
    }
}
`
I add the script to an empty object. And I'm doing a build. I forgot to say that the manifest is also adding your code, as well as I transfer your aar library to plugins / android.

![image](https://user-images.githubusercontent.com/57084802/82177794-a4edb600-98eb-11ea-8d2c-9be7620a1034.png)

`Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
 java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.android.installreferrer.api.InstallReferrerClient found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
  Duplicate class com.android.installreferrer.api.InstallReferrerClient$1 found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
  Duplicate class com.android.installreferrer.api.InstallReferrerClient$Builder found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerClient$InstallReferrerResponse found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerClientImpl found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerClientImpl$1 found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerClientImpl$ClientState found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.InstallReferrerStateListener found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.api.ReferrerDetails found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.android.installreferrer.commons.InstallReferrerCommons found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.google.android.finsky.externalreferrer.IGetInstallReferrerService found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
Duplicate class com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy found in modules classes.jar (:com.android.installreferrer.installreferrer-1.0:) and classes.jar (:installreferrer-1.1.2:)
`

I tried to describe the maximum in detail)

**Comment by uerceg** [comment]
@hungrygamedev Thanks for the explanation, gave it a shot, but still facing the same problem from [this comment](https://github.com/uerceg/play-install-referrer-unity/issues/5#issuecomment-629872728).

Here's my project attached: [InstallReferrerUnity.zip](https://github.com/uerceg/play-install-referrer-unity/files/4642943/InstallReferrerUnity.zip)

Is there any chance you can make it reproduce the issue you are seeing?

**Comment by hungrygamedev** [comment]
Is it possible to somehow check it without sending it to google play console?

**Comment by hungrygamedev** [comment]
I did not understand your question a bit. A problem arises every time I do it.

**Comment by uerceg** [comment]
Problem I am facing is that I can't reproduce this error you are seeing above at all. Is it possible for you to create empty dummy Unity app to which you will add my and FB SDK where you will be able to reproduce this error and send me over that project?

**Comment by hungrygamedev** [comment]
yes, shure

**Comment by hungrygamedev** [comment]
I make it )) https://dropmefiles.com/75im0

**Comment by uerceg** [comment]
Awesome, thanks, will take a look. :+1:

**Comment by uerceg** [comment]
@hungrygamedev 

Okay, this example app is totally different from mine since it has all bunch of dependencies added to `Assets/Plugin/Android` folder which I don't have in mine. And it seems pretty obvious why this doesn't work. What ever added these dependencies to `Assets/Plugins/Android` folder among other things added `com.android.installreferrer.installreferrer-1.0.aar` as well. I see you moved dependency from my plugin in there as well (but location doesn't really matter, so all good) so `installreferrer-1.1.2.aar` exists in there as well. And these two naturally conflict one with another because they contain lots of shared code inside.

I am not sure what exactly added `com.android.installreferrer.installreferrer-1.0.aar` dependency and does it have some kind of hard dependency to that particular version so if you maybe remove that one, things will break for FB SDK or whatever else. 

When it comes to my plugin, it doesn't really care how did you end up with install referrer AAR dependency as long as you have one. Only thing to be aware of is that some fields which plugin is reading from install referrer library might exist only as of certain library version. For example [Google Play Instant parameter](https://developer.android.com/reference/com/android/installreferrer/api/ReferrerDetails#getGooglePlayInstantParam()) was not present in initial release (1.0) of the library whose AAR you have adde to your app. So my plugin will probably return `null` in that case since it will be unable to read it. If you're fine with that, than feel free to remove `installreferrer-1.1.2.aar` which my plugin added to your app and hopefully your error should be gone.

Thanks for reporting this, I will add troubleshooting part to the repository as well to describe issue like this one and how to handle it.

At the moment I am not sure how to handle native library dependencies other than packing them to Unity plugin and app itself, so will try to see if there is a way to maybe state dependencies like this to be part of the Android app's Gradle configuration file and avoid these conflicts when building an app. Not too optimistic that I'll find anything having in mind that even FB SDK seems to be packing these dependencies in same way I did it my plugin, but will try to research on this topic a bit.

Please lemme know if things worked for you after removal of `installreferrer-1.1.2.aar` which my plugin added to your app.

Cheers

**Comment by hungrygamedev** [comment]
I left your aar, and deleted the FB install referrer aar. So far, everything is working.
"5 minutes normal flight" (C) Yuri Gagarin :)

**Comment by uerceg** [comment]
In theory both ways should work (deleting AAR which FB or my plugin added) since at the end of the day FB SDK should probably be aiming at API from install referrer library 1.0 which also exists in 1.1.2 so there should **probably** be no issues at all. But of course, can't say this with 100% certainty since I don't really know in which exact way is FB plugin using the API.

If you are fine with not having instant parameter value in my plugin, feel free to remove AAR my plugin added and use the one FB is adding to maybe be on a safe side that you won't accidentally break anything inside of the FB plugin.

**Comment by uerceg** [comment]
In case you have any further question on this topic feel free to comment or reopen if there's need for that.

Cheers!
